#!/bin/sh

KINDLE_ROOT=${KINDLE_ROOT:-/mnt/us}
MANAGER_DIR=${MANAGER_DIR:-$KINDLE_ROOT/kindle-manager}
SERVER_URL=${SERVER_URL:-http://YOUR_MAC_IP:8787}
AUTH_TOKEN_FILE=${AUTH_TOKEN_FILE:-$MANAGER_DIR/auth-token}
POLL_SECONDS=${POLL_SECONDS:-60}
HEARTBEAT_SECONDS=${HEARTBEAT_SECONDS:-300}
DEVICE_ID=${DEVICE_ID:-kindle-voyage}
