#!/bin/sh

BASE_DIR=/mnt/us/kindle-photoframe
CACHE_DIR="$BASE_DIR/cache"
STATE_DIR="$BASE_DIR/state"
FBINK=/mnt/us/libkh/bin/fbink
INTERVAL_MIN_SECONDS=600
INTERVAL_MAX_SECONDS=1200
SYNC_INTERVAL_SECONDS=60
MANUAL_FULL_REFRESH_DELAY_SECONDS=120
SERVER_URL=http://YOUR_MAC_IP:8787
AUTH_TOKEN_FILE="$BASE_DIR/auth-token"
NEXT_KEY_CODES="109"
PREV_KEY_CODES="104"
EXIT_KEY_CODES="330 116"
PAGEPRESS_DEVICE_NAME=fsr_keypad
TOUCH_DEVICE_NAME=cyttsp4_mt
POWER_DEVICE_NAME=max77696-onkey
INPUT_GRABBER="$BASE_DIR/kindle-evgrab-cat"
X_CONTROLS="$BASE_DIR/kindle-xcontrols"
APP_VERSION=0.4.1
DAY_START_HOUR=7
NIGHT_START_HOUR=22
DAY_FRONTLIGHT_LEVEL=4
FRONTLIGHT_CHECK_SECONDS=60
